services:
  postgres:
    container_name: yfin_scraper_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: yfin_scraper_db  # TODO: use secrets for db_name
      POSTGRES_USER: yfin_scraper  # TODO: use secrets for user
      POSTGRES_PASSWORD: pass  # TODO: use secrets for password
      PGPORT: 5434
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bullseye_trader

  api:
    container_name: yfin_scraper
    stdin_open: true
    tty: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_api
    volumes:
      - .:/yfin_scraper
    depends_on:
      - postgres
    networks:
      - bullseye_trader

networks:
  bullseye_trader:
    name: bullseye_trader
    external: true
