FROM python:3.12

# Update package lists
RUN apt-get update
RUN apt-get install -y ghostscript python3-tk ffmpeg libsm6 libxext6 tesseract-ocr

# Set up work directory
COPY . /yfin_scraper
WORKDIR /yfin_scraper

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

CMD ["fastapi", "run", "api.py", "--port", "80", "--reload"]
