repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
-   repo: https://github.com/pycqa/pylint
    rev: v3.2.6
    hooks:
    - id: pylint
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
    - id: mypy
    types: [python]
    args: [--strict]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
    - id: commitizen
